import Head from "next/head";
import useSWR from "swr";
import useGeoLocation from "../hooks/useGeoLocation";
import Table from "react-bootstrap/Table";
export default function Home() {
  const location = useGeoLocation();

  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const { data, error } = useSWR("http://localhost:5000/current", fetcher);

  if (error) return <div className="celsius">Hups jokin meni pieleen.</div>;
  if (!data) return <p className="celsius">Loading...</p>;

  let temp = data.main.temp;
  let feelsLike = data.main.feels_like;
  const postIds = data.weather.map((weather) => weather.description);

  let timestamp = data.dt;
  const date = new Date(timestamp * 1000);
  const options = {
    timeZone: "Europe/Helsinki",
    hour12: false,
    hour: "2-digit",
    minute: "2-digit",
  };
  const updated = date.toLocaleString("en-GB", options);

  return (
    <>
      <Head>
        <title>Weather-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main variant="dark">
        <div className="celsius">
          <h1 className="celsius">Location: {data.name}</h1>
          <img src={data.icon} alt="icon" />
          <p>Temperature: {Math.round(temp)}°C</p>
          <p>Wind: {data.wind.speed} M/S</p>
          <p>Pressure: {data.main.pressure} hPa</p>
          <p>Humidity: {data.main.humidity} %</p>
          <p>
            Feels like: {Math.round(feelsLike)}°C, {postIds}
          </p>
          <p>Last updated: {updated}</p>
        </div>
      </main>
    </>
  );
}
